"""
Django settings for office_mgt project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1*hocxh#ihjovwg_u#g!)0#dzr)14(y*^)dk(q-!i@hd249%af'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

JWT_SECRET = 'django-insecure-c(dco6u23%32b_ax66-w#bzt4zy2e+&8l(n1ee+ym@7_y!lnk&'

# Application definition

INSTALLED_APPS = [
    'authentication',
    'office_mgt',
    'utils',
    'deliveries',
    'employee_travels',
    'visitors',
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'office_mgt.urls'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'office_mgt.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'calebkemboi5@gmail.com'
EMAIL_HOST_PASSWORD = 'ncfd xsrw eeql lamj'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailAuthBackend',  # Custom Email Authentication
    'django.contrib.auth.backends.ModelBackend',  # Default Django authentication
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'utils.User'

JAZZMIN_SETTINGS = {
    # General UI Configuration
    "site_title": "AgriConnect",
    "site_header": "AgriConnect",
    # "site_logo": "fas fa-leaf",  # Using a Font Awesome leaf icon as a placeholder logo
    # "login_logo": "fas fa-leaf",  # Matching icon for the login page
    "copyright": "© 2025 AgriConnect",

    # Navigation Menu
    "navigation_expanded": False,  # Keeps the menu compact by default
    "hide_apps": [],  # Show all apps for now
    "hide_models": [],  # Show all models

    # Custom Styling
    "custom_css": None,  # Placeholder for future custom CSS (e.g., "css/agriconnect.css")
    "custom_js": None,  # No custom JS needed yet

    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://agriconnect.support", "new_window": True},
        {"model": "auth.User"},  # Dropdown for user management
    ],

    # UI Components
    "show_sidebar": True,  # Keep the sidebar for navigation
    "show_ui_builder": True,  # Enable UI builder for interactive tweaking
    "related_modal_active": True,  # Modals for related fields enhance usability
    "sticky_header": True,  # Fixed header for easy access
    "changeform_format": "horizontal_tabs",  # Sleek form layout

    # Icon Configuration
    "icons": {
        # Default Django apps
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",
        "sessions.Session": "fas fa-clock",
    },
}

JAZZMIN_UI_TWEAKS = {
    # Text Sizing
    "navbar_small_text": True,    # Compact navbar text
    "footer_small_text": True,    # Compact footer text
    "body_small_text": False,     # Normal body text for readability
    "brand_small_text": True,     # Compact branding text

    # Colors and Styling
    "brand_colour": "navbar-dark",     # Dark navbar branding
    "accent": "accent-success",        # Green accent for an agricultural vibe
    "navbar": "navbar-dark",           # Dark navbar background
    "no_navbar_border": False,         # Border for visual separation
    "sidebar": "sidebar-dark-primary", # Dark sidebar with primary tones

    # Sidebar Navigation
    "sidebar_nav_small_text": True,    # Compact sidebar text
    "sidebar_disable_expand": False,   # Allow sidebar expansion
    "sidebar_nav_child_indent": True,  # Indent child items for hierarchy
    "sidebar_nav_compact_style": True, # Sleek, compact sidebar
    "sidebar_nav_legacy_style": False, # Modern sidebar style
    "sidebar_nav_flat_style": True,    # Flat design for a clean look

    # Theme
    "theme": "darkly",  # A balanced dark theme from Bootswatch

    # Button Classes
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"  # Outline style for a modern touch
    },}