# Generated by Django 5.1 on 2025-02-28 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_travels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visit_purpose', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField()),
                ('visitor_checked_out', models.BooleanField(default=False, null=True)),
                ('visitor_first_name', models.CharField(max_length=200)),
                ('visitor_last_name', models.CharField(max_length=200)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_email', models.CharField(max_length=15)),
                ('visit_time', models.TimeField()),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_travels.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
