# Generated by Django 5.1 on 2025-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_user_reset_otp_user_reset_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reset_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
