# Generated by Django 5.1 on 2025-02-28 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=200)),
                ('employee_second_name', models.CharField(max_length=200)),
                ('employee_email', models.CharField(max_length=200)),
                ('employee_phone', models.CharField(max_length=100)),
                ('supervisors', models.ManyToManyField(blank=True, related_name='subordinates', to='employee_travels.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('travel_title', models.CharField(max_length=200)),
                ('travel_applied_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('travel_purpose', models.CharField(max_length=200)),
                ('travel_date_from', models.DateTimeField()),
                ('travel_date_to', models.DateTimeField()),
                ('travel_destination', models.CharField(max_length=50)),
                ('mode_of_transport', models.CharField(max_length=100)),
                ('travel_budget', models.CharField(max_length=100)),
                ('travel_approval_status', models.CharField(max_length=20)),
                ('date_expenses_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('travel_expenses_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('expenses_description', models.TextField(blank=True, null=True)),
                ('expenses_date_submitted', models.DateField(blank=True, null=True)),
                ('expenses_approval_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_travels.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
