# Generated by Django 5.1 on 2025-03-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_travels', '0003_remove_employee_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisors',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee_travels.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='travels',
            name='travel_applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
