# Generated by Django 5.1 on 2025-03-03 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_travels', '0004_remove_employee_supervisors_employee_is_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='supervisor_note',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
