# Generated by Django 5.1 on 2025-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_travels', '0006_alter_travels_supervisor_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='expenses_approval_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
