# Generated by Django 5.1 on 2025-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_travels', '0007_alter_travels_expenses_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='expenses_approval_Status',
            field=models.CharField(max_length=50),
        ),
    ]
