# Generated by Django 5.1 on 2025-03-25 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=200)),
                ('delivery_description', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
